version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: brokagefirm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: brokagefirmdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: brokagefirm-app
    container_name: brokagefirma-pp
    depends_on:
      - db
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://brokagefirm-db:5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      db_host: brokagefirm-db

volumes:
  db_data: